package rules
 
import com.lparce.model.Product
import java.util.Date
import java.math.BigDecimal

rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(35);
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(45);
		productObject.setAmount(productObject.getAmount().add(new  BigDecimal(10)).setScale(2,BigDecimal.ROUND_UP));
		productObject.setDate(new Date());
		System.out.println(productObject);
	end